### ISSUE TITLE
TypeError: object of type 'numpy.int32' has no len()

### ISSUE THREAD

**Issue by vinayakkailas** [Belval/CRNN#18]
When i run testing i get the below error

(vinayak) C:\Users\vinayak\Documents\github\CRNN-1\CRNN>python run.py -ex ../sam
ples --test --restore
Restoring
Checkpoint is valid
0
Loading data
examples 10
Traceback (most recent call last):
  File "run.py", line 118, in <module>
    main()
  File "run.py", line 111, in main
    args.restore
  File "C:\Users\vinayak\Documents\github\CRNN-1\CRNN\crnn.py", line 53, in __in
it__
    self.__data_manager = DataManager(batch_size, model_path, examples_path, max
_image_width, train_test_ratio, self.__max_char_count)
  File "C:\Users\vinayak\Documents\github\CRNN-1\CRNN\data_manager.py", line 26,
 in __init__
    self.test_batches = self.__generate_all_test_batches()
  File "C:\Users\vinayak\Documents\github\CRNN-1\CRNN\data_manager.py", line 108
, in __generate_all_test_batches
    (-1)
  File "C:\Users\vinayak\Documents\github\CRNN-1\CRNN\utils.py", line 17, in spa
rse_tuple_from
    indices.extend(zip([n]*len(seq), [i for i in range(len(seq))]))
TypeError: object of type 'numpy.int32' has no len()

**Comment by Belval** [comment]
The images in the samples/ folder are the images displayed in the README.md, not valid testing examples as they do not have a ground truth in the filename.

**Comment by Belval** [comment]
You can use this dataset to test https://node1.belval.org/test_dataset.zip or generate a new one using https://github.com/Belval/TextRecognitionDataGenerator.

**Comment by vinayakkailas** [comment]
i found a workaround. I commented sparse_tuple_from call from __generate_all_test_batches and used only batch_x and batch_y to run test. Anyways we just need batch_x only to do the prediction. 

And yes, i had modified the filenames in the samples folder

Thanks

**Comment by colorful101** [comment]
hello，i also have this problem during training the new model.
the command i used is :
python run.py -m /save/ -ex F:/code/ICDAR/2015part/ch4_training_word_images_gt/ --train

and then i get the same error message as you 
Traceback (most recent call last):
  File "run.py", line 119, in <module>
    main()
  File "run.py", line 99, in main
    args.restore
  File "C:\Users\CRNN\CRNN\crnn.py", line 53, in __init__
    self.__data_manager = DataManager(batch_size, model_path, examples_path, max_image_width, train_test_ratio, self.__max_char_count)
  File "C:\Users\CRNN\CRNN\data_manager.py", line 28, in __init__
    self.test_batches = self.__generate_all_test_batches()
  File "C:\Users\CRNN\CRNN\data_manager.py", line 112, in __generate_all_test_batches
    batch_dt = sparse_tuple_from(np.reshape(np.array(raw_batch_la),-1))
  File "C:\Users\CRNN\CRNN\utils.py", line 20, in sparse_tuple_from
    indices.extend(zip([n] * len(list(seq)), [i for i in range(len(list(seq)))]))
TypeError: 'numpy.int32' object is not iterable

i use this model on dataset icdar2015,and the filename is just like the samples.
could you please help me to solve this problem ,thanks a lot.
@vinayakkailas  @Belval
