### ISSUE TITLE
CHAR_VECTOR is correct?

### ISSUE THREAD

**Issue by yoyoyo-yo** [Belval/CRNN#60]
Thank you for your great job!

I tried your pretrained model, but got error.

Traceback (most recent call last):
  File "/Users/yoshitonagaoka/dev/miniconda3/envs/deepscholar-crnn/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/Users/yoshitonagaoka/dev/miniconda3/envs/deepscholar-crnn/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/yoshitonagaoka/dev/miniconda3/envs/deepscholar-crnn/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [512,71] rhs shape= [512,70]
	 [[{{node save/Assign_1}}]]

I fixed CHAR_VECTOR in run.py like below, and worked well.
#CHAR_VECTOR = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-'.!?,\"&"
CHAR_VECTOR = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-'.!?,&"

Please tell the correct CHAR_VECTOR for your pretrained model.

**Comment by mrtpk** [comment]
Please see the issue #61 
It should be CHAR_VECTOR = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-'.!?,\""
